# NumPy Playground

This notebook outlines the fundimentals of working with NumPy.

In [1]:
import numpy as np


## The Basics

In [8]:
a = np.array([1, 2, 3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [3]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get dimension
b.ndim

2

In [5]:
b.shape

(2, 3)

In [10]:
# get the datatype of items
a.dtype

dtype('int16')

In [11]:
# get the size of an item in bytes
a.itemsize

2

In [13]:
# get the total size
a.nbytes

6

## Accessing/Changing specific elements, rows, columns, etc.

In [19]:
two_d = np.array([[1,2,3,4,5,6,7],[7,8,9,10,11,12,13]])
two_d.shape

(2, 7)

In [20]:
two_d[1,5]

12

In [22]:
# get a specific row
two_d[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# get a specific column
two_d[:, 2]

array([3, 9])

In [37]:
# Gettin' fancy 💃🏻 [startIndex:endIndex:stepSize]
two_d[0, 1:6:2] # first row, elements 2 until 6, every second item

array([2, 4, 6])

In [38]:
# Changing elements
two_d[1,5] = 42
print(two_d)

[[ 1  2  3  4  5  6  7]
 [ 7  8  9 10 11 42 13]]


In [43]:
# Updating a column
two_d[:,2] = 7
print(two_d)

print("\n")

two_d[:,5] = [10,11]
print(two_d)

[[ 1  2  7  4  5 10  7]
 [ 7  8  7 10 11 11 13]]


[[ 1  2  7  4  5 10  7]
 [ 7  8  7 10 11 11 13]]


## Initializing Different Types of Arrays

In [54]:
# All 0s matrix
one_d_zero = np.zeros(5, dtype='int32') # single dimension
print(one_d_zero)

print("\n")

two_by_four = np.zeros((2,4)) # multi dimension
print(two_by_four)

print("\n")

# All ones
one_d_one = np.ones(5)
print(one_d_one)

print("\n")

# All 42s
life_the_universe_and_everything = np.full((2,2), 42)
print(life_the_universe_and_everything)

[0 0 0 0 0]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[1. 1. 1. 1. 1.]


[[42 42]
 [42 42]]


In [67]:
# Random decimal numbers
rfloat = np.random.rand(2,2)
print(rfloat)

print("\n")

# Random integers, size is optional, first arg is the bounds (exclusive) if one unnamed arg given
rint = np.random.randint(42, size=rfloat.shape)
print(rint)

[[0.48251224 0.88736334]
 [0.18659216 0.88948616]]


[[20 15]
 [ 1 11]]


## Pass by reference

In [68]:
a = np.array([1, 2, 3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [69]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Math

In [70]:
a = np.array([1, 2, 3, 4])

In [71]:
a + 2

array([3, 4, 5, 6])

In [77]:
print(a.dtype)

b = np.array([2, 2, 1, 2])
print(b.dtype)

c = a / b
print(c)
print(c.dtype)

int64
int64
[0.5 1.  3.  2. ]
float64


In [83]:
np.cos(a)

array([[0.54030231, 0.54030231, 0.54030231],
       [0.54030231, 0.54030231, 0.54030231]])

In [86]:
a = np.array([1, 2, 3, 4])
np.min(a)

1

In [99]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.max(b))
print("\n")
print(np.max(b, axis=1))
print("\n")
print(np.sum(b))
print("\n")
print(np.sum(b, axis=0))

8


[4 8]


36


[ 6  8 10 12]


## Reorganising Arrays

In [104]:
# Reshaping 
b4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

aft = b4.reshape((4,2))
print(aft)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [110]:
# Vertically stacking
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.vstack([a, b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [109]:
# Horizontal stack

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.hstack([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

## Misc

In [116]:
# Load from text file
filedata = np.genfromtxt('numbers.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [118]:
filedata > 20

array([[False, False,  True, False,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [119]:
# Create a new array basedon on a condition
filedata[filedata > 20]

array([ 21., 196.,  75.,  34.,  42.,  33., 766.,  75.,  55.,  22.,  33.,
       999.,  78.,  76.,  88.])

In [124]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Create a new array by plucking particular indexes
a[[0,2,4]]

array([1, 3, 5])

In [125]:
# What columns have a value > 20
np.any(filedata > 20, axis=0)

array([False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [126]:
# Array showing what values meet a condition
((filedata > 20) & (filedata < 50))

array([[False, False,  True, False, False, False, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])